title: Página de David
author: nxvaexe - David Ventura Serrano
email: dvsventuras@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Esta es la descripción de la página donde se describe lo describible del sitio.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
